window.addEventListener('load', () => {
  const calculatePricesBtn = document.getElementById('calculate');
  calculatePricesBtn.addEventListener('click', calculateAll);
});

// ITERATION 1

function updateSubtotal(product) {
  // get the price of product from price span in "product" (parameter will be defined in another function) and store it in a variable
  const price = product.querySelector('.price span');

  // get the quantity selected by user from quantity input and and store it in a variable
  const quantity = product.querySelector('.quantity input');

  // multiply the price by number of products and get subtotal
  const subTotProduct = price.textContent * quantity.value;

  // update subtotal on the page
  product.querySelector('.subtotal').textContent = subTotProduct;

  // return the value of subtotal so it can be used by other functions calling this one
  return subTotProduct;
}

function calculateAll() {
  // ITERATION 2

  // store product list in a variable, selecting all elements with class product in the document (node list)
  const prodsList = document.querySelectorAll('.product');

  let subtotalEveryProd = 0; // accumulator for values produced by every function call using our prodsList

  // iterate over list of products, add up every node list item generated by function call on updateSubtotal using our prodsList
  for (let i = 0; i < prodsList.length; i++) {
    subtotalEveryProd += updateSubtotal(prodsList[i]);
  }

  // ITERATION 3

  // store values created dynamically in the DOM coming from the subtotal class of every product
  const prodsListPrices = document.querySelectorAll('.subtotal');

  let totalPrice = 0; // accumulator for values coming from node list generated by selecting (prodsListPrices)

  // iterate over prodListPrices, add up values, transform a string into a number (values in the class subtotal are NOT originally numbers)
  for (let i = 0; i < prodsListPrices.length; i++) {
    totalPrice += Number(prodsListPrices[i].textContent);
  }

  // update DOM, change number shown in totalPrice
  document.querySelector('#total-value span').textContent = totalPrice;

  // return totalPrice (I don't know whether I'll need it further on)
  return totalPrice;
}

// ITERATION 4

function removeProduct(event) {
  const target = event.currentTarget;
  console.log('The target in remove is:', target);
  //... your code goes here
}

// ITERATION 5

function createProduct() {
  //... your code goes here
}

window.addEventListener('load', () => {
  const calculatePricesBtn = document.getElementById('calculate');
  calculatePricesBtn.addEventListener('click', calculateAll);

  //... your code goes here
});
